" This file is automatically generated by test-syntax from testing.vim

fun! Test_basic() abort
    call TestSyntax(g:test_packdir . '/syntax/testdata/basic.go',
        \ [
        \ [['goPackage', 1, 8]],
        \ [],
        \ [['goImport', 1, 7], ['goString', 8, 12]],
        \ [],
        \ [['goDeclaration', 1, 5]],
        \ [['goVar', 2, 5], ['goType', 10, 16], ['goString', 19, 29]],
        \ [],
        \ [],
    \ ])
endfun
