" This file is automatically generated by test-syntax from testing.vim

fun! Test_directive() abort
    call TestSyntax(g:test_packdir . '/syntax/testdata/directive.go',
        \ [
        \ [['goBuildTagStart', 1, 1], ['goBuildTag', 3, 3], ['goBuildKeyword', 4, 4], ['goBuildTag', 10, 13]],
        \ [],
        \ [['goGenerateKW', 1, 1], ['goGenerate', 14, 17]],
        \ [],
        \ [['goPackage', 1, 8]],
        \ [],
        \ [['goCompilerDir', 1, 12]],
        \ [['goDeclaration', 1, 5], ['goType', 17, 20]],
        \ [['goStatement', 2, 8], ['goDecimalInt', 9, 10]],
        \ [],
    \ ])
endfun
