" This file is automatically generated by test-syntax from testing.vim

fun! Test_fmt() abort
    call TestSyntax(g:test_packdir . '/syntax/testdata/fmt.go',
        \ [
        \ [['goPackage', 1, 8]],
        \ [],
        \ [['goVar', 1, 4]],
        \ [['goString', 6, 6], ['goFormatSpecifier', 7, 7], ['goString', 9, 9], ['goFormatSpecifier', 11, 11], ['goString', 14, 14], ['goFormatSpecifier', 15, 15], ['goString', 20, 20]],
        \ [['goString', 6, 6], ['goFormatSpecifier', 7, 7], ['goString', 10, 11]],
        \ [['goString', 6, 6], ['goFormatSpecifier', 10, 10], ['goString', 12, 15]],
        \ [['goString', 6, 6], ['goFormatSpecifier', 7, 7], ['goString', 11, 11], ['goFormatSpecifier', 13, 13], ['goString', 20, 20], ['goFormatSpecifier', 21, 21], ['goString', 24, 24], ['goFormatSpecifier', 25, 25], ['goString', 30, 30], ['goFormatSpecifier', 31, 31], ['goString', 34, 34]],
        \ [],
    \ ])
endfun
