" This file is automatically generated by test-syntax from testing.vim

fun! Test_fmt() abort
    call TestSyntax(g:test_packdir . '/syntax/testdata/fmt.go',
        \ [
        \ [['goPackage', 1, 8]],
        \ [],
        \ [['goVar', 1, 4]],
        \ [['goString', 12, 12], ['goFormatSpecifier', 13, 13], ['goString', 15, 15], ['goFormatSpecifier', 17, 17], ['goString', 20, 20], ['goFormatSpecifier', 21, 21], ['goString', 26, 26]],
        \ [['goString', 12, 12], ['goFormatSpecifier', 13, 13], ['goString', 16, 17]],
        \ [['goString', 12, 12], ['goFormatSpecifier', 16, 16], ['goString', 18, 21]],
        \ [['goString', 12, 12], ['goFormatSpecifier', 13, 13], ['goString', 17, 17], ['goFormatSpecifier', 19, 19], ['goString', 26, 26], ['goFormatSpecifier', 27, 27], ['goString', 30, 30], ['goFormatSpecifier', 31, 31], ['goString', 36, 36], ['goFormatSpecifier', 37, 37], ['goString', 40, 40]],
        \ [['goString', 12, 29]],
        \ [],
    \ ])
endfun
