" This file is automatically generated by test-syntax from testing.vim

scriptencoding utf-8
call gopher#init#config()

fun! Test_gomod() abort
    call TestSyntax(g:test_packdir . '/syntax/testdata/go.mod',
        \ [
        \ [['gomodKeywords', 1, 7]],
        \ [],
        \ [['gomodKeywords', 1, 3]],
        \ [],
        \ [['gomodComment', 1, 11]],
        \ [['gomodKeywords', 1, 8]],
        \ [['gomodVersion', 29, 29], ['gomodIndirect', 35, 46]],
        \ [['gomodVersion', 24, 43], ['gomodComment', 44, 56]],
        \ [['gomodVersion', 15, 48]],
        \ [],
        \ [],
        \ [['gomodComment', 1, 78]],
        \ [['gomodComment', 1, 79]],
        \ [['gomodKeywords', 1, 8], ['gomodReplace', 38, 40], ['gomodVersion', 68, 101]],
    \ ])
endfun
