" This file is automatically generated by test-syntax from testing.vim

scriptencoding utf-8
call gopher#init#config()

fun! Test_numbers() abort
    call TestSyntax(g:test_packdir . '/syntax/testdata/numbers.go',
        \ [
        \ [['goPackage', 1, 8]],
        \ [],
        \ [['goVar', 1, 4]],
        \ [['goDecimalInt', 11, 13]],
        \ [['goOctalInt', 11, 14]],
        \ [['goOctalInt', 11, 15]],
        \ [['goHexadecimalInt', 11, 16]],
        \ [['goBinaryInt', 11, 16]],
        \ [],
        \ [],
        \ [['goFloat', 11, 15]],
        \ [['goFloat', 11, 16]],
        \ [['goComment', 2, 23]],
        \ [],
        \ [['goDecimalInt', 13, 15]],
        \ [['goHexadecimalInt', 13, 16]],
        \ [],
        \ [['goDecimalInt', 12, 18]],
        \ [['goHexadecimalInt', 12, 18]],
        \ [['goBinaryInt', 12, 22]],
        \ [['goDecimalInt', 12, 12]],
        \ [],
    \ ])
endfun
