" This file is automatically generated by test-syntax from testing.vim

scriptencoding utf-8
call gopher#init#config()

fun! Test_struct() abort
    call TestSyntax(g:test_packdir . '/syntax/testdata/struct.go',
        \ [
        \ [['goPackage', 1, 8]],
        \ [],
        \ [['goDeclaration', 1, 5], ['goDeclaration', 8, 14]],
        \ [['goType', 4, 7], ['goRawString', 8, 8], ['goStructTagName', 9, 9], ['goRawString', 15, 19]],
        \ [['goType', 4, 7], ['goRawString', 8, 18]],
        \ [['goType', 4, 7], ['goRawString', 8, 8], ['goStructTagError', 9, 9], ['goRawString', 14, 20]],
        \ [['goType', 4, 7], ['goRawString', 8, 8], ['goStructTagError', 9, 9], ['goRawString', 14, 20]],
        \ [['goType', 4, 7], ['goRawString', 8, 8], ['goStructTagError', 9, 9], ['goRawString', 15, 21]],
        \ [],
    \ ])
endfun
