" This file is automatically generated by test-syntax from testing.vim

fun! Test_varconst() abort
    call TestSyntax(g:test_packdir . '/syntax/testdata/varconst.go',
        \ [
        \ [['goPackage', 1, 8]],
        \ [],
        \ [['goImport', 1, 7], ['goString', 8, 10]],
        \ [],
        \ [['goImport', 1, 7]],
        \ [['goString', 2, 4]],
        \ [['goString', 4, 6]],
        \ [['goString', 4, 6]],
        \ [],
        \ [],
        \ [['goVar', 1, 4], ['goString', 9, 11]],
        \ [],
        \ [['goVar', 1, 4]],
        \ [['goString', 6, 8]],
        \ [['goString', 6, 8]],
        \ [],
        \ [],
        \ [['goDeclaration', 1, 5]],
        \ [['goConst', 2, 7], ['goType', 10, 16], ['goString', 19, 23]],
        \ [],
        \ [['goConst', 2, 7]],
        \ [['goType', 5, 11], ['goString', 14, 18]],
        \ [],
        \ [],
    \ ])
endfun
